baseURL = "https://oscarcosta.github.io"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Oscar Costa"

# theme
theme = "anatole"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "G-YYN3WQBPEP"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
    unsafe=true

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"